### ISSUE TITLE
Cannot compile 

### ISSUE THREAD

**Issue by roscopecoltran** [nhurel/dim#1]
Hey,

Hope you are all well !

I could not compile the project and got the following error:

```bash
# github.com/nhurel/dim/wrapper/dockerClient
wrapper/dockerClient/dockerClient.go:125:8: undefined: "github.com/nhurel/dim/vendor/github.com/docker/docker/reference".Named
wrapper/dockerClient/dockerClient.go:126:14: undefined: "github.com/nhurel/dim/vendor/github.com/docker/docker/reference".ParseNamed
wrapper/dockerClient/dockerClient.go:155:20: undefined: "github.com/nhurel/dim/vendor/github.com/docker/docker/reference".DefaultHostname
wrapper/dockerClient/dockerClient.go:207:8: undefined: "github.com/nhurel/dim/vendor/github.com/docker/docker/reference".Named
wrapper/dockerClient/dockerClient.go:208:14: undefined: "github.com/nhurel/dim/vendor/github.com/docker/docker/reference".ParseNamed
```

Cheers,
Rosco

**Comment by nhurel** [comment]
Hello,

Did you just clone the repository and ran `go build`or did you try to update the dependencies ? Current vendored source of docker do declare the interface `Named` and the function `ParseNamed` as you can see here : https://github.com/nhurel/dim/blob/master/vendor/github.com/docker/docker/reference/reference.go#L25,L71

HTH,
Nathan

**Comment by roscopecoltran** [comment]
Hey Nathan,

Hope you are all well !

Yes, I updated the vendors, so I started to update **dim** code and update imports. I haven't realize how much docker packages have become a mess since they forked docker-ce; no clear docs for migrating them.
 
So I haven't tested it yet, but it compiles the code. Here is the fork url: https://github.com/sniperkit/dim

If you spot any errors from your side, I would be more than happy to finish the update as I would like to add faceted search, add automatically some labels and index the content of docker files by parsing them (search apk packages installed for alpine based images).

Thanks in advance for your reply.

Cheers,
Rosco

**Comment by nhurel** [comment]
Hello,
I can't compile your version on my side but if you manage to have `make test` and `make integration_tests` succeed you should be fine.

indeed following with docker update is a bit hard. Don't hesitate to submit a PR with dependency updates. 
Looking forward to seeing what features you will add to this project ;)

Nathan
